import os
import pathlib
import torch

from glob import glob
from torch.utils.data import DataLoader
from torchvision import transforms
from typing import Tuple, List
from PIL import Image

from src.data_loader.abstract_data_loader import AbstractDataLoader
from src.util.constants import SAD_DATASET_PATH, SADD_IMAGES_FAULTY_PATH

"""
STFPM code modified and taken from https://github.com/gdwang08/STFPM
Original code is under GNU GPLv3, thus same license must apply to this project
"""


class MVTecDatasetLazy(torch.utils.data.Dataset):
    """
    Load images lazily on every call, saving RAM space.
    """

    def __init__(self, image_list: List,
                 transform: torch.nn.Module | transforms.Compose = None):
        super().__init__()
        self._image_list = image_list
        if transform is None:
            self._transform = transforms.ToTensor()
        else:
            self._transform = transform

    def __len__(self) -> int:
        return len(self._image_list)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, int]:
        img_data = Image.open(self._image_list[idx]).convert('RGB')
        image = self._transform(img_data)
        # We do not have any labels for now, thus 0
        # Data, Label
        return image, 0


class MVTecDatasetLazyTest(MVTecDatasetLazy):
    """
    Data Loader for test data. Returns additionally img file name and export
    path to save the test images generated by the corresponding model
    evaluator.
    """

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, str, str]:
        img_data = Image.open(self._image_list[idx]).convert('RGB')
        image = self._transform(img_data)
        # We use the img name and path for export of test img
        # Data, Img File Name, Img File Path
        path = pathlib.PurePath(self._image_list[idx])
        return image, path.name, str(path)


class MVTecDatasetRAM(torch.utils.data.Dataset):
    """
    Load all training and test images into RAM on initialization (30GB+ ?),
    thus speeding up training.
    """

    def __init__(self, image_list: List,
                 transform: torch.nn.Module | transforms.Compose = None):
        super().__init__()
        self.image_list = image_list
        if transform is None:
            self._transform = transforms.ToTensor()
        else:
            self._transform = transform
        self.dataset = self._load_dataset()

    def _load_dataset(self) -> List:
        return [Image.open(p).convert('RGB') for p in self.image_list]

    def __len__(self) -> int:
        return len(self.dataset)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, int]:
        image = self._transform(self.dataset[idx])
        # We do not have any labels in for now, thus 0
        # Data, Label
        return image, 0


class STFPMDataLoader(AbstractDataLoader):

    def __init__(self, batch_size: int, load_into_memory: bool,
                 dataset_name: List[pathlib.Path]):
        super().__init__(batch_size=batch_size)
        self._dataset_name = dataset_name
        if load_into_memory:
            self._dataset = MVTecDatasetRAM
        else:
            self._dataset = MVTecDatasetLazy

    def get_data_loaders(self) -> Tuple[
        DataLoader, DataLoader, List[DataLoader]]:
        transform = transforms.Compose([
            transforms.Resize([256, 256]),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])
        ])

        image_list_train = []
        image_list_val = []
        image_list_test_good = []

        for subset in self._dataset_name:
            image_list_train += sorted(
                glob(str(subset.joinpath('train', '*.png'))))
            image_list_val += sorted(
                glob(str(subset.joinpath('val', '*.png'))))
            image_list_test_good += sorted(
                glob(str(subset.joinpath('test', '*.png'))))

        image_list_test_bad = sorted(glob(os.path.join(SADD_IMAGES_FAULTY_PATH,
                                                       'test', '*.png')))

        train_dataset = self._dataset(image_list_train, transform=transform)
        train_loader = DataLoader(train_dataset,
                                  batch_size=self._batch_size, shuffle=True,
                                  drop_last=False)

        val_dataset = self._dataset(image_list_val, transform=transform)
        val_loader = DataLoader(val_dataset, batch_size=self._batch_size,
                                shuffle=False, drop_last=False)

        test_good_dataset = MVTecDatasetLazyTest(image_list_test_good,
                                                 transform=transform)
        test_good_loader = DataLoader(test_good_dataset,
                                      batch_size=self._batch_size,
                                      shuffle=False, drop_last=False)
        test_bad_dataset = MVTecDatasetLazyTest(image_list_test_bad,
                                                transform=transform)
        test_bad_loader = DataLoader(test_bad_dataset,
                                     batch_size=self._batch_size,
                                     shuffle=False, drop_last=False)

        return train_loader, val_loader, [test_good_loader, test_bad_loader]
